# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fourstring/CLionProjects/lsmtree

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fourstring/CLionProjects/lsmtree

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fourstring/CLionProjects/lsmtree/CMakeFiles /home/fourstring/CLionProjects/lsmtree/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fourstring/CLionProjects/lsmtree/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LSMTree

# Build rule for target.
LSMTree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LSMTree
.PHONY : LSMTree

# fast build rule for target.
LSMTree/fast:
	$(MAKE) -f CMakeFiles/LSMTree.dir/build.make CMakeFiles/LSMTree.dir/build
.PHONY : LSMTree/fast

#=============================================================================
# Target rules for targets named SSTable

# Build rule for target.
SSTable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SSTable
.PHONY : SSTable

# fast build rule for target.
SSTable/fast:
	$(MAKE) -f CMakeFiles/SSTable.dir/build.make CMakeFiles/SSTable.dir/build
.PHONY : SSTable/fast

#=============================================================================
# Target rules for targets named MemTable

# Build rule for target.
MemTable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MemTable
.PHONY : MemTable

# fast build rule for target.
MemTable/fast:
	$(MAKE) -f CMakeFiles/MemTable.dir/build.make CMakeFiles/MemTable.dir/build
.PHONY : MemTable/fast

#=============================================================================
# Target rules for targets named KVStore

# Build rule for target.
KVStore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KVStore
.PHONY : KVStore

# fast build rule for target.
KVStore/fast:
	$(MAKE) -f CMakeFiles/KVStore.dir/build.make CMakeFiles/KVStore.dir/build
.PHONY : KVStore/fast

#=============================================================================
# Target rules for targets named gzip_test

# Build rule for target.
gzip_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gzip_test
.PHONY : gzip_test

# fast build rule for target.
gzip_test/fast:
	$(MAKE) -f CMakeFiles/gzip_test.dir/build.make CMakeFiles/gzip_test.dir/build
.PHONY : gzip_test/fast

#=============================================================================
# Target rules for targets named DiskTable

# Build rule for target.
DiskTable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DiskTable
.PHONY : DiskTable

# fast build rule for target.
DiskTable/fast:
	$(MAKE) -f CMakeFiles/DiskTable.dir/build.make CMakeFiles/DiskTable.dir/build
.PHONY : DiskTable/fast

#=============================================================================
# Target rules for targets named lsmtree

# Build rule for target.
lsmtree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lsmtree
.PHONY : lsmtree

# fast build rule for target.
lsmtree/fast:
	$(MAKE) -f CMakeFiles/lsmtree.dir/build.make CMakeFiles/lsmtree.dir/build
.PHONY : lsmtree/fast

#=============================================================================
# Target rules for targets named fs_test

# Build rule for target.
fs_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fs_test
.PHONY : fs_test

# fast build rule for target.
fs_test/fast:
	$(MAKE) -f CMakeFiles/fs_test.dir/build.make CMakeFiles/fs_test.dir/build
.PHONY : fs_test/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named correctness

# Build rule for target.
correctness: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 correctness
.PHONY : correctness

# fast build rule for target.
correctness/fast:
	$(MAKE) -f CMakeFiles/correctness.dir/build.make CMakeFiles/correctness.dir/build
.PHONY : correctness/fast

#=============================================================================
# Target rules for targets named MurmurHash

# Build rule for target.
MurmurHash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MurmurHash
.PHONY : MurmurHash

# fast build rule for target.
MurmurHash/fast:
	$(MAKE) -f CMakeFiles/MurmurHash.dir/build.make CMakeFiles/MurmurHash.dir/build
.PHONY : MurmurHash/fast

#=============================================================================
# Target rules for targets named persistent

# Build rule for target.
persistent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 persistent
.PHONY : persistent

# fast build rule for target.
persistent/fast:
	$(MAKE) -f CMakeFiles/persistent.dir/build.make CMakeFiles/persistent.dir/build
.PHONY : persistent/fast

bloom_filter/MurmurHash.o: bloom_filter/MurmurHash.cpp.o

.PHONY : bloom_filter/MurmurHash.o

# target to build an object file
bloom_filter/MurmurHash.cpp.o:
	$(MAKE) -f CMakeFiles/MurmurHash.dir/build.make CMakeFiles/MurmurHash.dir/bloom_filter/MurmurHash.cpp.o
.PHONY : bloom_filter/MurmurHash.cpp.o

bloom_filter/MurmurHash.i: bloom_filter/MurmurHash.cpp.i

.PHONY : bloom_filter/MurmurHash.i

# target to preprocess a source file
bloom_filter/MurmurHash.cpp.i:
	$(MAKE) -f CMakeFiles/MurmurHash.dir/build.make CMakeFiles/MurmurHash.dir/bloom_filter/MurmurHash.cpp.i
.PHONY : bloom_filter/MurmurHash.cpp.i

bloom_filter/MurmurHash.s: bloom_filter/MurmurHash.cpp.s

.PHONY : bloom_filter/MurmurHash.s

# target to generate assembly for a file
bloom_filter/MurmurHash.cpp.s:
	$(MAKE) -f CMakeFiles/MurmurHash.dir/build.make CMakeFiles/MurmurHash.dir/bloom_filter/MurmurHash.cpp.s
.PHONY : bloom_filter/MurmurHash.cpp.s

correctness.o: correctness.cc.o

.PHONY : correctness.o

# target to build an object file
correctness.cc.o:
	$(MAKE) -f CMakeFiles/correctness.dir/build.make CMakeFiles/correctness.dir/correctness.cc.o
.PHONY : correctness.cc.o

correctness.i: correctness.cc.i

.PHONY : correctness.i

# target to preprocess a source file
correctness.cc.i:
	$(MAKE) -f CMakeFiles/correctness.dir/build.make CMakeFiles/correctness.dir/correctness.cc.i
.PHONY : correctness.cc.i

correctness.s: correctness.cc.s

.PHONY : correctness.s

# target to generate assembly for a file
correctness.cc.s:
	$(MAKE) -f CMakeFiles/correctness.dir/build.make CMakeFiles/correctness.dir/correctness.cc.s
.PHONY : correctness.cc.s

disktable/DiskTable.o: disktable/DiskTable.cpp.o

.PHONY : disktable/DiskTable.o

# target to build an object file
disktable/DiskTable.cpp.o:
	$(MAKE) -f CMakeFiles/DiskTable.dir/build.make CMakeFiles/DiskTable.dir/disktable/DiskTable.cpp.o
.PHONY : disktable/DiskTable.cpp.o

disktable/DiskTable.i: disktable/DiskTable.cpp.i

.PHONY : disktable/DiskTable.i

# target to preprocess a source file
disktable/DiskTable.cpp.i:
	$(MAKE) -f CMakeFiles/DiskTable.dir/build.make CMakeFiles/DiskTable.dir/disktable/DiskTable.cpp.i
.PHONY : disktable/DiskTable.cpp.i

disktable/DiskTable.s: disktable/DiskTable.cpp.s

.PHONY : disktable/DiskTable.s

# target to generate assembly for a file
disktable/DiskTable.cpp.s:
	$(MAKE) -f CMakeFiles/DiskTable.dir/build.make CMakeFiles/DiskTable.dir/disktable/DiskTable.cpp.s
.PHONY : disktable/DiskTable.cpp.s

disktable/sstable/SSTable.o: disktable/sstable/SSTable.cpp.o

.PHONY : disktable/sstable/SSTable.o

# target to build an object file
disktable/sstable/SSTable.cpp.o:
	$(MAKE) -f CMakeFiles/SSTable.dir/build.make CMakeFiles/SSTable.dir/disktable/sstable/SSTable.cpp.o
.PHONY : disktable/sstable/SSTable.cpp.o

disktable/sstable/SSTable.i: disktable/sstable/SSTable.cpp.i

.PHONY : disktable/sstable/SSTable.i

# target to preprocess a source file
disktable/sstable/SSTable.cpp.i:
	$(MAKE) -f CMakeFiles/SSTable.dir/build.make CMakeFiles/SSTable.dir/disktable/sstable/SSTable.cpp.i
.PHONY : disktable/sstable/SSTable.cpp.i

disktable/sstable/SSTable.s: disktable/sstable/SSTable.cpp.s

.PHONY : disktable/sstable/SSTable.s

# target to generate assembly for a file
disktable/sstable/SSTable.cpp.s:
	$(MAKE) -f CMakeFiles/SSTable.dir/build.make CMakeFiles/SSTable.dir/disktable/sstable/SSTable.cpp.s
.PHONY : disktable/sstable/SSTable.cpp.s

filesystem_test.o: filesystem_test.cpp.o

.PHONY : filesystem_test.o

# target to build an object file
filesystem_test.cpp.o:
	$(MAKE) -f CMakeFiles/fs_test.dir/build.make CMakeFiles/fs_test.dir/filesystem_test.cpp.o
.PHONY : filesystem_test.cpp.o

filesystem_test.i: filesystem_test.cpp.i

.PHONY : filesystem_test.i

# target to preprocess a source file
filesystem_test.cpp.i:
	$(MAKE) -f CMakeFiles/fs_test.dir/build.make CMakeFiles/fs_test.dir/filesystem_test.cpp.i
.PHONY : filesystem_test.cpp.i

filesystem_test.s: filesystem_test.cpp.s

.PHONY : filesystem_test.s

# target to generate assembly for a file
filesystem_test.cpp.s:
	$(MAKE) -f CMakeFiles/fs_test.dir/build.make CMakeFiles/fs_test.dir/filesystem_test.cpp.s
.PHONY : filesystem_test.cpp.s

gzip_test.o: gzip_test.cpp.o

.PHONY : gzip_test.o

# target to build an object file
gzip_test.cpp.o:
	$(MAKE) -f CMakeFiles/gzip_test.dir/build.make CMakeFiles/gzip_test.dir/gzip_test.cpp.o
.PHONY : gzip_test.cpp.o

gzip_test.i: gzip_test.cpp.i

.PHONY : gzip_test.i

# target to preprocess a source file
gzip_test.cpp.i:
	$(MAKE) -f CMakeFiles/gzip_test.dir/build.make CMakeFiles/gzip_test.dir/gzip_test.cpp.i
.PHONY : gzip_test.cpp.i

gzip_test.s: gzip_test.cpp.s

.PHONY : gzip_test.s

# target to generate assembly for a file
gzip_test.cpp.s:
	$(MAKE) -f CMakeFiles/gzip_test.dir/build.make CMakeFiles/gzip_test.dir/gzip_test.cpp.s
.PHONY : gzip_test.cpp.s

kvstore.o: kvstore.cc.o

.PHONY : kvstore.o

# target to build an object file
kvstore.cc.o:
	$(MAKE) -f CMakeFiles/KVStore.dir/build.make CMakeFiles/KVStore.dir/kvstore.cc.o
.PHONY : kvstore.cc.o

kvstore.i: kvstore.cc.i

.PHONY : kvstore.i

# target to preprocess a source file
kvstore.cc.i:
	$(MAKE) -f CMakeFiles/KVStore.dir/build.make CMakeFiles/KVStore.dir/kvstore.cc.i
.PHONY : kvstore.cc.i

kvstore.s: kvstore.cc.s

.PHONY : kvstore.s

# target to generate assembly for a file
kvstore.cc.s:
	$(MAKE) -f CMakeFiles/KVStore.dir/build.make CMakeFiles/KVStore.dir/kvstore.cc.s
.PHONY : kvstore.cc.s

lsmtree/LSMTree.o: lsmtree/LSMTree.cpp.o

.PHONY : lsmtree/LSMTree.o

# target to build an object file
lsmtree/LSMTree.cpp.o:
	$(MAKE) -f CMakeFiles/LSMTree.dir/build.make CMakeFiles/LSMTree.dir/lsmtree/LSMTree.cpp.o
.PHONY : lsmtree/LSMTree.cpp.o

lsmtree/LSMTree.i: lsmtree/LSMTree.cpp.i

.PHONY : lsmtree/LSMTree.i

# target to preprocess a source file
lsmtree/LSMTree.cpp.i:
	$(MAKE) -f CMakeFiles/LSMTree.dir/build.make CMakeFiles/LSMTree.dir/lsmtree/LSMTree.cpp.i
.PHONY : lsmtree/LSMTree.cpp.i

lsmtree/LSMTree.s: lsmtree/LSMTree.cpp.s

.PHONY : lsmtree/LSMTree.s

# target to generate assembly for a file
lsmtree/LSMTree.cpp.s:
	$(MAKE) -f CMakeFiles/LSMTree.dir/build.make CMakeFiles/LSMTree.dir/lsmtree/LSMTree.cpp.s
.PHONY : lsmtree/LSMTree.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/lsmtree.dir/build.make CMakeFiles/lsmtree.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/lsmtree.dir/build.make CMakeFiles/lsmtree.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/lsmtree.dir/build.make CMakeFiles/lsmtree.dir/main.cpp.s
.PHONY : main.cpp.s

memtable/MemTable.o: memtable/MemTable.cpp.o

.PHONY : memtable/MemTable.o

# target to build an object file
memtable/MemTable.cpp.o:
	$(MAKE) -f CMakeFiles/MemTable.dir/build.make CMakeFiles/MemTable.dir/memtable/MemTable.cpp.o
.PHONY : memtable/MemTable.cpp.o

memtable/MemTable.i: memtable/MemTable.cpp.i

.PHONY : memtable/MemTable.i

# target to preprocess a source file
memtable/MemTable.cpp.i:
	$(MAKE) -f CMakeFiles/MemTable.dir/build.make CMakeFiles/MemTable.dir/memtable/MemTable.cpp.i
.PHONY : memtable/MemTable.cpp.i

memtable/MemTable.s: memtable/MemTable.cpp.s

.PHONY : memtable/MemTable.s

# target to generate assembly for a file
memtable/MemTable.cpp.s:
	$(MAKE) -f CMakeFiles/MemTable.dir/build.make CMakeFiles/MemTable.dir/memtable/MemTable.cpp.s
.PHONY : memtable/MemTable.cpp.s

persistence.o: persistence.cc.o

.PHONY : persistence.o

# target to build an object file
persistence.cc.o:
	$(MAKE) -f CMakeFiles/persistent.dir/build.make CMakeFiles/persistent.dir/persistence.cc.o
.PHONY : persistence.cc.o

persistence.i: persistence.cc.i

.PHONY : persistence.i

# target to preprocess a source file
persistence.cc.i:
	$(MAKE) -f CMakeFiles/persistent.dir/build.make CMakeFiles/persistent.dir/persistence.cc.i
.PHONY : persistence.cc.i

persistence.s: persistence.cc.s

.PHONY : persistence.s

# target to generate assembly for a file
persistence.cc.s:
	$(MAKE) -f CMakeFiles/persistent.dir/build.make CMakeFiles/persistent.dir/persistence.cc.s
.PHONY : persistence.cc.s

tests.o: tests.cpp.o

.PHONY : tests.o

# target to build an object file
tests.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests.cpp.o
.PHONY : tests.cpp.o

tests.i: tests.cpp.i

.PHONY : tests.i

# target to preprocess a source file
tests.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests.cpp.i
.PHONY : tests.cpp.i

tests.s: tests.cpp.s

.PHONY : tests.s

# target to generate assembly for a file
tests.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests.cpp.s
.PHONY : tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... LSMTree"
	@echo "... SSTable"
	@echo "... MemTable"
	@echo "... KVStore"
	@echo "... edit_cache"
	@echo "... gzip_test"
	@echo "... DiskTable"
	@echo "... lsmtree"
	@echo "... rebuild_cache"
	@echo "... fs_test"
	@echo "... tests"
	@echo "... correctness"
	@echo "... MurmurHash"
	@echo "... persistent"
	@echo "... bloom_filter/MurmurHash.o"
	@echo "... bloom_filter/MurmurHash.i"
	@echo "... bloom_filter/MurmurHash.s"
	@echo "... correctness.o"
	@echo "... correctness.i"
	@echo "... correctness.s"
	@echo "... disktable/DiskTable.o"
	@echo "... disktable/DiskTable.i"
	@echo "... disktable/DiskTable.s"
	@echo "... disktable/sstable/SSTable.o"
	@echo "... disktable/sstable/SSTable.i"
	@echo "... disktable/sstable/SSTable.s"
	@echo "... filesystem_test.o"
	@echo "... filesystem_test.i"
	@echo "... filesystem_test.s"
	@echo "... gzip_test.o"
	@echo "... gzip_test.i"
	@echo "... gzip_test.s"
	@echo "... kvstore.o"
	@echo "... kvstore.i"
	@echo "... kvstore.s"
	@echo "... lsmtree/LSMTree.o"
	@echo "... lsmtree/LSMTree.i"
	@echo "... lsmtree/LSMTree.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... memtable/MemTable.o"
	@echo "... memtable/MemTable.i"
	@echo "... memtable/MemTable.s"
	@echo "... persistence.o"
	@echo "... persistence.i"
	@echo "... persistence.s"
	@echo "... tests.o"
	@echo "... tests.i"
	@echo "... tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

